import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { AppShell } from '@/components/layout/AppShell';
import { api } from '@/api/client';
import { ROUTES } from '@/api/routes';
import { uploadBuild } from '@/api/upload';
import type { BuildsResponse } from '@core/ui/contracts.js';

export default function BuildsPanel() {
  const client = useQueryClient();
  const builds = useQuery({ queryKey: ['builds'], queryFn: () => api.get<BuildsResponse>(ROUTES.builds) });
  return <AppShell title="Bản build"><p className="text-muted-foreground text-sm">Bản build dùng cho local run, workflow và Device Farm.{builds.data ? ` File cất ở ${builds.data.root}.` : ''}</p>{builds.isError && <p role="alert" className="text-destructive mt-3">{(builds.error as Error).message}</p>}<div className="border-border mt-4 overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead><tr className="text-muted-foreground text-left"><th className="p-3">Môi trường</th><th className="p-3">Android (.apk)</th><th className="p-3">iOS (.ipa)</th></tr></thead><tbody>{builds.isPending && <tr><td colSpan={3} className="p-6 text-center">Đang tải…</td></tr>}{builds.data?.environments.map((row) => <tr key={row.env || 'shared'} className="border-border border-t"><td className="p-3"><b>{(row.env || 'Dùng chung').toUpperCase()}</b>{row.isDefault && row.env && <span className="text-muted-foreground ms-2 text-xs">mặc định</span>}</td><BuildCell row={row} platform="android" onDone={() => void Promise.all([client.invalidateQueries({ queryKey: ['builds'] }), client.invalidateQueries({ queryKey: ['state'] })])}/><BuildCell row={row} platform="ios" onDone={() => void Promise.all([client.invalidateQueries({ queryKey: ['builds'] }), client.invalidateQueries({ queryKey: ['state'] })])}/></tr>)}</tbody></table></div></AppShell>;
}
function BuildCell({ row, platform, onDone }: { row: BuildsResponse['environments'][number]; platform: 'android' | 'ios'; onDone: () => void }) { const [file, setFile] = useState<File | null>(null); const [progress, setProgress] = useState<number | null>(null); const upload = useMutation({ mutationFn: (picked: File) => uploadBuild(picked, { platform, ...(row.isDefault ? {} : { env: row.env }), persist: '1' }, setProgress), onSuccess: () => { toast.success('Đã lưu build.'); onDone(); setFile(null); }, onError: (e) => toast.error((e as Error).message), onSettled: () => setProgress(null) }); const build = row[platform]; const missing = row.missing.find((item) => item.platform === platform); return <td className="p-3 align-top"><div className="font-mono text-xs">{build?.path ?? (missing ? `✕ ${missing.path} — không thấy file` : 'Chưa có')}</div>{build?.sizeMb && <div className="text-muted-foreground text-xs">{build.sizeMb} MB</div>}<label className="border-border mt-2 inline-flex cursor-pointer rounded border px-2 py-1 text-xs">{upload.isPending ? 'Đang tải…' : build || missing ? 'Thay bản khác…' : 'Tải lên…'}<input className="sr-only" type="file" accept={platform === 'ios' ? '.ipa' : '.apk'} disabled={upload.isPending} onChange={(e) => { const picked = e.target.files?.[0]; if (picked) { setFile(picked); upload.mutate(picked); } e.currentTarget.value = ''; }}/></label>{file && <span className="ms-2 text-xs">{file.name}</span>}{progress !== null && <progress className="ms-2 h-2" value={progress} max={1}/>}</td>; }
