/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as HealingRouteImport } from './routes/healing'
import { Route as RunnerRouteImport } from './routes/runner'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as FarmRunIdRouteImport } from './routes/farm_.$runId'
import { Route as ProbeStreamRouteImport } from './routes/probe.stream'
import { Route as RunnerHistoryRouteImport } from './routes/runner_.history'
import { Route as ScenariosHistoryRouteImport } from './routes/scenarios_.history'
import { Route as TodoSlugRouteImport } from './routes/todo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const HealingRoute = HealingRouteImport.update({
  id: '/healing',
  path: '/healing',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerRoute = RunnerRouteImport.update({
  id: '/runner',
  path: '/runner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRunIdRoute = FarmRunIdRouteImport.update({
  id: '/farm_/$runId',
  path: '/farm/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeStreamRoute = ProbeStreamRouteImport.update({
  id: '/probe/stream',
  path: '/probe/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerHistoryRoute = RunnerHistoryRouteImport.update({
  id: '/runner_/history',
  path: '/runner/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosHistoryRoute = ScenariosHistoryRouteImport.update({
  id: '/scenarios_/history',
  path: '/scenarios/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoSlugRoute = TodoSlugRouteImport.update({
  id: '/todo/$slug',
  path: '/todo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/farm': typeof FarmRoute
  '/healing': typeof HealingRoute
  '/runner': typeof RunnerRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/farm/$runId': typeof FarmRunIdRoute
  '/probe/stream': typeof ProbeStreamRoute
  '/runner/history': typeof RunnerHistoryRoute
  '/scenarios/history': typeof ScenariosHistoryRoute
  '/todo/$slug': typeof TodoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/farm': typeof FarmRoute
  '/healing': typeof HealingRoute
  '/runner': typeof RunnerRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/farm/$runId': typeof FarmRunIdRoute
  '/probe/stream': typeof ProbeStreamRoute
  '/runner/history': typeof RunnerHistoryRoute
  '/scenarios/history': typeof ScenariosHistoryRoute
  '/todo/$slug': typeof TodoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/farm': typeof FarmRoute
  '/healing': typeof HealingRoute
  '/runner': typeof RunnerRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/farm_/$runId': typeof FarmRunIdRoute
  '/probe/stream': typeof ProbeStreamRoute
  '/runner_/history': typeof RunnerHistoryRoute
  '/scenarios_/history': typeof ScenariosHistoryRoute
  '/todo/$slug': typeof TodoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builds'
    | '/farm'
    | '/healing'
    | '/runner'
    | '/scenarios'
    | '/settings'
    | '/studio'
    | '/farm/$runId'
    | '/probe/stream'
    | '/runner/history'
    | '/scenarios/history'
    | '/todo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builds'
    | '/farm'
    | '/healing'
    | '/runner'
    | '/scenarios'
    | '/settings'
    | '/studio'
    | '/farm/$runId'
    | '/probe/stream'
    | '/runner/history'
    | '/scenarios/history'
    | '/todo/$slug'
  id:
    | '__root__'
    | '/'
    | '/builds'
    | '/farm'
    | '/healing'
    | '/runner'
    | '/scenarios'
    | '/settings'
    | '/studio'
    | '/farm_/$runId'
    | '/probe/stream'
    | '/runner_/history'
    | '/scenarios_/history'
    | '/todo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildsRoute: typeof BuildsRoute
  FarmRoute: typeof FarmRoute
  HealingRoute: typeof HealingRoute
  RunnerRoute: typeof RunnerRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  FarmRunIdRoute: typeof FarmRunIdRoute
  ProbeStreamRoute: typeof ProbeStreamRoute
  RunnerHistoryRoute: typeof RunnerHistoryRoute
  ScenariosHistoryRoute: typeof ScenariosHistoryRoute
  TodoSlugRoute: typeof TodoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healing': {
      id: '/healing'
      path: '/healing'
      fullPath: '/healing'
      preLoaderRoute: typeof HealingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner': {
      id: '/runner'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof RunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm_/$runId': {
      id: '/farm_/$runId'
      path: '/farm/$runId'
      fullPath: '/farm/$runId'
      preLoaderRoute: typeof FarmRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/stream': {
      id: '/probe/stream'
      path: '/probe/stream'
      fullPath: '/probe/stream'
      preLoaderRoute: typeof ProbeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner_/history': {
      id: '/runner_/history'
      path: '/runner/history'
      fullPath: '/runner/history'
      preLoaderRoute: typeof RunnerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios_/history': {
      id: '/scenarios_/history'
      path: '/scenarios/history'
      fullPath: '/scenarios/history'
      preLoaderRoute: typeof ScenariosHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/$slug': {
      id: '/todo/$slug'
      path: '/todo/$slug'
      fullPath: '/todo/$slug'
      preLoaderRoute: typeof TodoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildsRoute: BuildsRoute,
  FarmRoute: FarmRoute,
  HealingRoute: HealingRoute,
  RunnerRoute: RunnerRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  FarmRunIdRoute: FarmRunIdRoute,
  ProbeStreamRoute: ProbeStreamRoute,
  RunnerHistoryRoute: RunnerHistoryRoute,
  ScenariosHistoryRoute: ScenariosHistoryRoute,
  TodoSlugRoute: TodoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
