import { AstBuilder, GherkinClassicTokenMatcher, Parser } from '@cucumber/gherkin';
import { IdGenerator } from '@cucumber/messages';
import type { FeatureSpec, ScenarioSpec, StepSpec } from '../core/types.js';
import type { Registry } from '../core/registry.js';
import { normalizeTagList, tagCategory } from '../core/tagTaxonomy.js';
import { platformsForTags } from '../core/tagScope.js';
import { STEP_RULES } from './vocabulary.js';
import { parseContextualRowAction } from '../core/contextual.js';
import { normalizeHumanText } from '../core/text.js';

export class StepBindingError extends Error {
  constructor(
    readonly uri: string,
    readonly line: number,
    readonly text: string,
  ) {
    super(
      `${uri}:${line} — no step rule matches "${text}".\n` +
        `Steps must use the controlled vocabulary (see src/steps/vocabulary.ts).`,
    );
    this.name = 'StepBindingError';
  }
}

/** Case-insensitive label -> element ids index, so duplicate natural labels can
 * be resolved from the current screen instead of forcing users to write ids. */
function elementIndex(registry: Registry): Map<string, string[]> {
  const idx = new Map<string, string[]>();
  for (const el of Object.values(registry.raw.elements)) {
    idx.set(el.id.toLowerCase(), [el.id]);
    // Aliases enter the index exactly like the label, so every downstream rule
    // — screen scoping, canonical-id selection, the ambiguity warning — applies
    // to them unchanged. Uniqueness is enforced at load, so an alias can only
    // ever add the element that owns it.
    for (const name of [el.label, ...(el.aliases ?? [])]) {
      const key = name.toLowerCase();
      const ids = idx.get(key) ?? [];
      if (!ids.includes(el.id)) ids.push(el.id);
      idx.set(key, ids);
    }
  }
  return idx;
}

export function parseFeature(uri: string, source: string, registry: Registry): FeatureSpec {
  const parser = new Parser(new AstBuilder(IdGenerator.uuid()), new GherkinClassicTokenMatcher());
  const doc = parser.parse(source);
  const feature = doc.feature;
  if (!feature) throw new Error(`${uri} contains no Feature.`);

  const index = elementIndex(registry);
  const warnings: string[] = [];
  const resolveRef = (
    labelOrId: string,
    currentScreen?: string,
    dynamicValues: Set<string> = new Set(),
  ): { id: string; locatorParams?: Record<string, string> } => {
    const contextual = parseContextualRowAction(labelOrId);
    if (contextual) {
      const allTemplates = Object.values(registry.raw.elements).filter((element) =>
        element.template?.kind === 'rowAction' &&
        element.template.action === contextual.action,
      );
      const scopedTemplates = currentScreen
        ? allTemplates.filter((element) => element.screen === currentScreen)
        : allTemplates;
      // A shorthand element introduced just before this line may temporarily
      // set screen="auto". Do not discard the one globally unambiguous row
      // action template merely because that provisional screen does not match.
      let templates = scopedTemplates.length > 0 ? scopedTemplates : allTemplates;
      if (templates.length !== 1) {
        // Registry cleanup can lag behind scenario editing and leave automatic
        // copies of the same template under `auto` or a transient menu screen.
        // A single deliberate template is still unambiguous and carries the
        // proven locators; generated byproducts must not force an AI repair.
        const deliberate = allTemplates.filter((element) => element.provenance !== 'byproduct');
        if (deliberate.length === 1) templates = deliberate;
      }
      if (templates.length === 1) {
        return {
          id: templates[0]!.id,
          locatorParams: { rowText: contextual.rowText, action: contextual.action },
        };
      }
    }
    if (dynamicValues.has(labelOrId.toLocaleLowerCase())) {
      const templates = Object.values(registry.raw.elements).filter((element) =>
        element.template?.kind === 'text' &&
        (!currentScreen || element.screen === currentScreen),
      );
      if (templates.length === 1) {
        return { id: templates[0]!.id, locatorParams: { text: labelOrId } };
      }
    }
    const hits = index.get(labelOrId.toLowerCase());
    if (!hits?.length) {
      throw new Error(
        `Unknown element "${labelOrId}". Add it to the registry or fix the scenario wording.`,
      );
    }
    if (hits.length === 1) return { id: hits[0]! };

    const onScreen = currentScreen
      ? hits.filter((id) => registry.element(id).screen === currentScreen)
      : [];
    if (onScreen.length === 1) return { id: onScreen[0]! };

    // Historical generation may have minted two selector-less ids for the
    // same natural label on the same screen. That is registry duplication, not
    // user ambiguity. Reuse one deterministic canonical id and let discovery
    // enrich it instead of forcing a non-technical user to rename the step.
    const sameScreenHits = onScreen.length > 1
      ? onScreen
      : hits.every((id) => registry.element(id).screen === registry.element(hits[0]!).screen)
        ? hits
        : [];
    if (sameScreenHits.length > 1) {
      const chosen = canonicalElementId(sameScreenHits, registry);
      // Two ids for one label is usually one real element and a selector-less
      // twin left behind by an earlier generation — picking the one with
      // locators is not a guess and needs no warning. It is a guess only when
      // more than one carries locators of its own: then these are two different
      // controls that happen to share a name, and choosing by maturity can bind
      // the step to the wrong one without failing. That is the case worth
      // saying out loud; silence here looks exactly like success.
      const withLocators = sameScreenHits.filter((id) => hasLocators(registry.element(id)));
      if (withLocators.length > 1) {
        warnings.push(
          `Nhãn "${labelOrId}" trỏ tới ${withLocators.length} element khác nhau trên cùng màn hình ` +
            `"${registry.element(chosen).screen}": ${withLocators.join(', ')}. ` +
            `Đã tạm chọn "${chosen}" vì nhiều locator/lần chạy thành công hơn, nhưng đây là phỏng đoán — ` +
            'hãy đặt nhãn riêng cho từng element nếu chúng là hai control khác nhau.',
        );
      }
      return { id: chosen };
    }

    if (hits.length > 1) {
      // Naming the screens is the whole value of this message. It is fed back
      // into the draft-repair rounds, and "the current screen is unknown" sent
      // them renaming the step over and over when the screen was in fact known
      // and simply had no element by that name — a registry problem no wording
      // could fix.
      const where = hits
        .map((id) => `${id} (màn hình ${registry.element(id).screen})`)
        .join(', ');
      throw new Error(
        `Element label "${labelOrId}" ` +
          (currentScreen
            ? `does not exist on the current screen "${currentScreen}". It exists as: ${where}. ` +
              'Either use a label that exists on this screen, or the element is registered ' +
              'under the wrong screen.'
            : `exists on more than one screen and the current screen is unknown: ${where}. ` +
              'Use a more specific natural label.'),
      );
    }
    return { id: hits[0]! };
  };

  const bindStep = (
    kw: string,
    text: string,
    line: number,
    context: { screen?: string; dynamicValues: Set<string> },
  ): StepSpec => {
    for (const rule of STEP_RULES) {
      for (const pattern of rule.patterns) {
        const m = text.trim().match(pattern);
        if (m) {
          let rowAction: ReturnType<typeof parseContextualRowAction>;
          const resolvedRefs: Array<{ locatorParams?: Record<string, string> }> = [];
          const built = rule.build(m, (label) => {
            rowAction ??= parseContextualRowAction(label);
            const resolved = resolveRef(label, context.screen, context.dynamicValues);
            resolvedRefs.push({ locatorParams: resolved.locatorParams });
            return resolved.id;
          });
          let intent: typeof built = built;
          if ('element' in built && resolvedRefs[0]?.locatorParams) {
            intent = { ...built, locatorParams: resolvedRefs[0].locatorParams };
          }
          if (built.kind === 'dragDrop') {
            intent = {
              ...built,
              ...(resolvedRefs[0]?.locatorParams
                ? { sourceLocatorParams: resolvedRefs[0].locatorParams }
                : {}),
              ...(resolvedRefs[1]?.locatorParams
                ? { targetLocatorParams: resolvedRefs[1].locatorParams }
                : {}),
            };
          }
          if (intent.kind === 'tap' && rowAction) intent = { ...intent, rowAction };
          if (intent.kind === 'dragDrop') {
            const targetScreen = registry.element(intent.target).screen;
            if (targetScreen !== 'auto' || !context.screen) context.screen = targetScreen;
          } else if (intent.kind === 'ensureLoggedIn') {
            context.screen = 'home';
          } else if (intent.kind === 'openFeatureFromSearch') {
            context.screen = screenForFeature(intent.query, registry) ?? context.screen;
          } else if ('element' in intent) {
            const targetScreen = registry.element(intent.element).screen;
            if (targetScreen !== 'auto' || !context.screen) context.screen = targetScreen;
          }
          if (intent.kind === 'input' && isReusableRuntimeValue(intent.text)) {
            context.dynamicValues.add(intent.text.toLocaleLowerCase());
          }
          return {
            text: text.trim(),
            keyword: normalizeKeyword(kw),
            intent,
            line,
          };
        }
      }
    }
    throw new StepBindingError(uri, line, text.trim());
  };

  const background: StepSpec[] = [];
  const backgroundContext: { screen?: string; dynamicValues: Set<string> } = {
    dynamicValues: new Set(),
  };
  const scenarios: ScenarioSpec[] = [];
  // Only ownership, platform and runtime constraints inherit from Feature. Priority,
  // smoke/type and operational tags describe one scenario; inheriting them is
  // how an old `@smoke` accidentally turned every case in a file into smoke.
  const featureTags = normalizeTagList(feature.tags.map((t) => t.name)).filter((tag) => {
    const category = tagCategory(tag);
    return category === 'feature' || category === 'platform' || category === 'runtime';
  });

  for (const child of feature.children) {
    if (child.background) {
      for (const s of child.background.steps) {
        background.push(bindStep(s.keyword, s.text, s.location.line, backgroundContext));
      }
      continue;
    }
    const sc = child.scenario;
    if (!sc) continue;

    const tags = normalizeTagList([...featureTags, ...sc.tags.map((t) => t.name)]);
    const platforms = platformsForTags(tags);
    const scenarioContext: { screen?: string; dynamicValues: Set<string> } = {
      ...backgroundContext,
      dynamicValues: new Set(backgroundContext.dynamicValues),
    };

    if (sc.examples.length === 0) {
      scenarios.push({
        id: slug(`${feature.name}-${sc.name}`),
        name: sc.name,
        tags,
        platforms,
        steps: sc.steps.map((s) => bindStep(s.keyword, s.text, s.location.line, scenarioContext)),
      });
      continue;
    }

    // Scenario Outline: expand each Examples row into a concrete scenario so the
    // runner, the retry policy and the flake stats all operate on real cases.
    for (const ex of sc.examples) {
      const headers = ex.tableHeader?.cells.map((c) => c.value) ?? [];
      for (const [i, row] of (ex.tableBody ?? []).entries()) {
        const subs = new Map<string, string>();
        headers.forEach((h, j) => subs.set(h, row.cells[j]?.value ?? ''));
        const name = `${sc.name} [${headers.map((h) => `${h}=${subs.get(h)}`).join(', ')}]`;
        scenarios.push({
          id: slug(`${feature.name}-${sc.name}-${i}`),
          name,
          tags,
          platforms,
          steps: sc.steps.map((s) =>
            bindStep(s.keyword, substitute(s.text, subs), s.location.line, scenarioContext),
          ),
        });
      }
    }
  }

  return {
    uri,
    name: feature.name,
    background,
    scenarios,
    ...(warnings.length > 0 ? { warnings: [...new Set(warnings)] } : {}),
  };
}

function screenForFeature(feature: string, registry: Registry): string | undefined {
  const wanted = normalizeHumanText(feature);
  const exact = Object.values(registry.raw.screens).find((screen) =>
    normalizeHumanText(screen.title) === wanted,
  );
  if (exact) return exact.id;
  const partial = Object.values(registry.raw.screens).filter((screen) => {
    const title = normalizeHumanText(screen.title);
    return title.includes(wanted) || wanted.includes(title);
  });
  return partial.length === 1 ? partial[0]!.id : undefined;
}

function canonicalElementId(ids: string[], registry: Registry): string {
  return [...ids].sort((left, right) => {
    const a = registry.element(left);
    const b = registry.element(right);
    const maturity = elementMaturity(b) - elementMaturity(a);
    return maturity || left.length - right.length || left.localeCompare(right);
  })[0]!;
}

function elementMaturity(element: ReturnType<Registry['element']>): number {
  const candidates = Object.values(element.candidates)
    .reduce((count, list) => count + (list?.length ?? 0), 0);
  return candidates * 10 + (element.health?.resolutions ?? 0);
}

function isReusableRuntimeValue(value: string): boolean {
  const trimmed = value.trim();
  return Boolean(trimmed) && !/^\{\{.+\}\}$/.test(trimmed);
}

function substitute(text: string, subs: Map<string, string>): string {
  return text.replace(/<([^>]+)>/g, (whole, key: string) => subs.get(key) ?? whole);
}

function normalizeKeyword(kw: string): StepSpec['keyword'] {
  const k = kw.trim();
  if (k === 'Given' || k === 'When' || k === 'Then' || k === 'And' || k === 'But') return k;
  return 'And';
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

/** Whether an element carries a locator of its own on any platform. */
function hasLocators(element: ReturnType<Registry['element']>): boolean {
  return Object.values(element.candidates).some((list) => (list?.length ?? 0) > 0);
}
