import { useRef, useState } from 'react';
import { AppShell } from '@/components/layout/AppShell';
import { StatusPill } from '@/components/StatusPill';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useAppState } from '@/hooks/useAppState';
import { api } from '@/api/client';
import { when } from '@/lib/datetime';
import type { ReportView } from '@core/ui/contracts.js';

const PLATFORMS = ['web', 'android', 'ios'] as const;

export default function RunnerHistoryPanel({ runId }: { runId?: string }) {
  const state = useAppState((s) => s.reports);
  const reports = state.data?.filter((r): r is ReportView => typeof r === 'object' && r !== null && 'id' in r) ?? [];
  const [platform, setPlatform] = useState(reports.find((item) => item.id === runId)?.platform ?? PLATFORMS.find((item) => reports.some((r) => r.platform === item)) ?? 'web');
  const [week, setWeek] = useState('all'); const [device, setDevice] = useState('all'); const [picked, setPicked] = useState(runId ?? '');
  const available = reports.filter((r) => r.platform === platform).sort((a, b) => Date.parse(b.startedAt) - Date.parse(a.startedAt));
  const weeks = [...new Set(available.map((r) => weekKey(r.startedAt)).filter(Boolean))];
  const devices = [...new Set(available.map((r) => r.device).filter((v): v is string => Boolean(v)))];
  const filtered = available.filter((r) => (week === 'all' || weekKey(r.startedAt) === week) && (device === 'all' || r.device === device));
  const report = filtered.find((r) => r.id === picked) ?? filtered[0];
  const choose = (next: string) => { setPlatform(next); setWeek('all'); setDevice('all'); setPicked(''); };
  return <AppShell title="E2E History" description="Lọc report theo platform, tuần và thiết bị."><section className="flex flex-col gap-4">
    <div role="tablist" aria-label="Platform report" className="flex flex-wrap gap-2">{PLATFORMS.map((item) => <Button key={item} size="sm" role="tab" variant={platform === item ? 'default' : 'outline'} disabled={!reports.some((r) => r.platform === item)} onClick={() => choose(item)}>{item} ({reports.filter((r) => r.platform === item).length})</Button>)}</div>
    <Card><CardContent className="flex flex-wrap gap-3 p-4"><label className="text-sm">Tuần<select className="input mt-1" value={week} onChange={(e) => { setWeek(e.target.value); setPicked(''); }}><option value="all">Tất cả ({available.length})</option>{weeks.map((item) => <option key={item} value={item}>{weekLabel(item)} — {available.filter((r) => weekKey(r.startedAt) === item).length}</option>)}</select></label><label className="text-sm">Thiết bị<select className="input mt-1" value={device} disabled={devices.length < 2} onChange={(e) => { setDevice(e.target.value); setPicked(''); }}><option value="all">Tất cả ({devices.length || 1})</option>{devices.map((item) => <option key={item}>{item}</option>)}</select></label></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Lượt chạy ({filtered.length})</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-muted-foreground text-left"><th>Thời gian</th><th>Kết quả</th><th>Pass</th><th>Fail</th><th>Thời lượng</th><th>Tag</th><th>Thiết bị</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className={`cursor-pointer border-t ${report?.id === item.id ? 'bg-muted' : ''}`} onClick={() => setPicked(item.id)}><td className="py-2">{when(item.startedAt)}</td><td><StatusPill status={item.status} /></td><td>{item.counters?.passed ?? '—'}</td><td>{item.counters?.failed ?? '—'}</td><td>{duration(item)}</td><td>{item.tag ?? '—'}</td><td>{item.device ?? '—'}</td></tr>)}{!filtered.length && <tr><td colSpan={7} className="text-muted-foreground py-6 text-center">Không có lượt chạy khớp bộ lọc.</td></tr>}</tbody></table></div></CardContent></Card>
    {report && <ReportDetail report={report} />}
  </section></AppShell>;
}

function ReportDetail({ report }: { report: ReportView }) { const [network, setNetwork] = useState<string | null>(null); return <section className="space-y-4"><Card><CardContent className="p-4"><div className="flex gap-2"><StatusPill status={report.status}/><a href={report.url} target="_blank" rel="noreferrer" className="text-sm underline">Mở report</a></div><iframe title={`Report ${report.id}`} src={report.url} className="border-border mt-3 h-[550px] w-full rounded border"/></CardContent></Card>{report.wholeVideoUrls?.map((url) => <VideoWithChapters key={url} url={url} report={report} />)}{report.videoUrls?.filter((url) => !report.wholeVideoUrls?.includes(url)).map((url) => <video key={url} controls preload="metadata" className="max-h-[420px] w-full rounded border" src={url} />)}{report.shotUrls && <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{report.shotUrls.map((shot) => <a key={shot.url} href={shot.url} target="_blank" rel="noreferrer"><img className="border-border rounded border" src={shot.url} alt={shot.name}/><span className="text-xs">{shot.onFailure ? 'khi fail' : shot.name}</span></a>)}</div>}{report.networkLogUrl && <details onToggle={(e) => { if ((e.currentTarget as HTMLDetailsElement).open && network === null) void api.getText(report.networkLogUrl!).then(setNetwork).catch((err: Error) => setNetwork(`Không đọc được log: ${err.message}`)); }}><summary>Network log</summary><NetworkLog text={network} /></details>}</section>; }
function VideoWithChapters({ url, report }: { url: string; report: ReportView }) { const video = useRef<HTMLVideoElement>(null); const [skip, setSkip] = useState(0); return <Card><CardContent className="space-y-2 p-4"><video ref={video} controls preload="metadata" className="max-h-[460px] w-full rounded" src={url} onLoadedMetadata={(e) => { const duration = e.currentTarget.duration; if (report.testSeconds && Number.isFinite(duration)) { const value = Math.max(0, duration - report.testSeconds - 2); setSkip(value); if (value >= 1) e.currentTarget.currentTime = value; } }} />{skip >= 1 && <p className="text-muted-foreground text-xs">Bắt đầu ở {skip.toFixed(0)}s, bỏ qua phần cài app/tạo session.</p>}{(report.chapters?.length ?? 0) > 1 && <ol className="flex flex-wrap gap-2">{report.chapters!.map((chapter) => <li key={`${chapter.name}-${chapter.at}`}><Button size="sm" variant="outline" onClick={() => { if (video.current) { video.current.currentTime = skip + chapter.at; void video.current.play(); } }}>{formatSeconds(skip + chapter.at)} {chapter.name}</Button></li>)}</ol>}</CardContent></Card>; }
function NetworkLog({ text }: { text: string | null }) { if (text === null) return <pre className="bg-muted mt-2 rounded p-3 text-xs">Đang tải…</pre>; return <pre className="bg-muted mt-2 max-h-72 overflow-auto rounded p-3 text-xs whitespace-pre-wrap">{text.split('\n').filter(Boolean).map((line, index) => <span key={index} className={/ FAILED |\s[45]\d{2}\s/.test(line) ? 'text-destructive' : /\s[34]\d{2}\s/.test(line) ? 'text-amber-700 dark:text-amber-400' : 'text-status-pass'}>{line}{'\n'}</span>)}</pre>; }
function weekKey(iso: string) { const date = new Date(iso); if (Number.isNaN(date.getTime())) return ''; const day = (date.getDay() + 6) % 7; date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - day); return date.toISOString().slice(0, 10); }
function weekLabel(key: string) { return `Tuần ${new Date(`${key}T00:00:00`).toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit' })}`; }
function duration(report: ReportView) { const from = Date.parse(report.startedAt); const to = Date.parse(report.finishedAt ?? ''); if (Number.isNaN(from) || Number.isNaN(to) || to < from) return '—'; const seconds = Math.round((to - from) / 1000); return seconds < 90 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }
function formatSeconds(value: number) { return `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, '0')}`; }
