/**
 * Snapshot of the real UI at runtime.
 *
 * UiObservation is the source of truth for element discovery — not LLM
 * guesses from documents. Missing attributes stay undefined; never invent values.
 * Hierarchy is preserved via parentId/childIds to resolve duplicate labels.
 */

export type ObservationPlatform = 'android' | 'ios' | 'web';
export type ObservationSource = 'native' | 'webview' | 'browser' | 'appium-mcp';

export interface ObservedElement {
  /** Unique id assigned during this observation session — not a locator. */
  id: string;
  /**
   * The driver/provider that originated this element (G02).
   * Allows downstream code to distinguish 'appium-mcp' ids from 'appium' ids.
   */
  provider?: string;
  /**
   * The original element id as assigned by the provider BEFORE TestPilot
   * renaming (G02). Used to resolve MCP findElement() results back to
   * TestPilot's observation id (tp-el-N).
   */
  providerElementId?: string;
  /** ARIA role (web) / widget class (native). */
  role?: string;
  /** Visible trimmed text. */
  text?: string;
  /** aria-label / content-desc / iOS accessibilityLabel. */
  accessibilityLabel?: string;
  /** Android resource-id, package prefix stripped. */
  resourceId?: string;
  /** data-testid / accessibilityIdentifier. */
  testId?: string;
  placeholder?: string;
  /** Current value for inputs. */
  value?: string;
  /** XPath — generated by driver, may be fragile. */
  xpath?: string;
  /** CSS selector — web only. */
  css?: string;
  /** Bounding box in device-independent pixels (origin = top-left). */
  bounds?: { x: number; y: number; width: number; height: number };
  visible: boolean;
  enabled?: boolean;
  interactive?: boolean;
  selected?: boolean;
  checked?: boolean;
  focused?: boolean;
  /** Position among same-role siblings — fallback of last resort. */
  index?: number;
  /** Parent element id within this observation. */
  parentId?: string;
  /** Child element ids within this observation. */
  childIds?: string[];
  /** Extra platform-specific attributes (not covered above). */
  attributes?: Record<string, string>;
}

export interface UiObservation {
  /** Unique id for this snapshot. */
  id: string;
  timestamp: string;
  platform: ObservationPlatform;
  source: ObservationSource;
  context: {
    appPackage?: string;
    activity?: string;
    bundleId?: string;
    webContext?: string;
    /** Appium session id — for G03 same-session verification. */
    appiumSessionId?: string;
    /** Device identifier (UDID / serial). */
    deviceId?: string;
    /** MCP client/session id if this observation came from Appium MCP. */
    mcpSessionId?: string;
  };
  screen?: { name?: string; confidence?: number };
  elements: ObservedElement[];
  screenshot?: { path?: string; width?: number; height?: number };
  /** Raw page source / DOM for debugging and offline replay. */
  rawSource?: string;
}
