/**
 * Chạy suite: sinh tiến trình CLI, theo dõi vòng đời của nó, dừng nó khi cần.
 *
 * Phần này chạm tới máy theo nghĩa nặng nhất trong cả project — nó mở tiến
 * trình bấm vào thiết bị thật. Nên nó ở `src/runner/`, cạnh `prereq.ts`, chứ
 * không ở cùng chỗ với phần phục vụ HTTP.
 *
 * Tiến trình con được theo dõi ở HAI nơi và cả hai đều cần thiết: `runChildren`
 * để dừng được trong phiên này, và `OrphanTracker` ghi PID xuống đĩa để lần
 * khởi động sau dọn được thứ mà SIGKILL bỏ lại. Một tiến trình test mồ côi
 * không chỉ tốn CPU — nó vẫn bấm vào điện thoại thật trong khi không nút nào
 * dừng được nó.
 *
 * Nội dung giữ nguyên từng dòng so với bản trong `src/ui/server.ts`.
 */
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { OrphanTracker } from '../core/orphans.js';
import { loadConfig, devicesOf, type TestPilotConfig } from '../config.js';
import { beginActiveRun, endActiveRun } from '../ui/activeRuns.js';
import { cleanLog, stopWebDriverAgent } from './prereq.js';

/**
 * Tiến trình test đang sống trong phiên này.
 *
 * Export để đường tắt lúc server nhận SIGINT/SIGTERM còn dừng được chúng: tiến
 * trình cha thoát mà con còn sống là đúng cảnh `OrphanTracker` sinh ra để dọn.
 */
export const runChildren = new Set<ReturnType<typeof spawn>>();
/**
 * MỘT bản duy nhất cho cả tiến trình, và đó là điều kiện đúng đắn chứ không
 * phải tiện tay.
 *
 * `add()`/`remove()` ghi cả mảng trong RAM xuống file. Hai bản `load()` là hai
 * bản sao đọc ở hai thời điểm khác nhau, và bản ghi sau sẽ khôi phục lại những
 * PID mà bản kia vừa dọn — sổ PID nói dối đúng vào lúc nó được sinh ra để nói
 * thật. Suýt xảy ra khi tách file này ra khỏi `server.ts`: phần dọn lúc khởi
 * động ở bên kia, phần ghi khi chạy ở bên này.
 */
export const orphans = OrphanTracker.load();

/**
 * Theo dõi một tiến trình con cho tới lúc nó chết.
 *
 * Set trong RAM đủ để nút Dừng làm việc khi server còn sống. Tệp PID là cho
 * trường hợp server KHÔNG còn sống — lúc đó Set biến mất còn tiến trình con
 * thì không, vì giết cha không giết con.
 */
/**
 * Lệnh chạy một CLI của dự án — và cách gọi nó đổi theo chỗ mã đang nằm.
 *
 * Chạy từ mã nguồn thì đó là `tsx src/cli/run.ts`. Chạy từ gói đã phát hành
 * thì không có `src/`, không có `tsx`, và `node_modules/.bin` của thư mục làm
 * việc chẳng liên quan gì tới nơi runner được cài.
 *
 * Nên phân giải theo VỊ TRÍ CỦA CHÍNH FILE NÀY, không theo thư mục làm việc.
 * Bản đầu dùng `path.resolve('node_modules/.bin/tsx')` và nó chạy suốt trong
 * lúc phát triển, vì thư mục làm việc tình cờ luôn là gốc repo. Trên một chiếc
 * máy cài từ npm thì nó trỏ vào một đường dẫn không tồn tại, và lượt chạy đầu
 * tiên hỏng bằng ENOENT — thứ không nói được gì về nguyên nhân.
 */
export function cliCommand(name: 'run' | 'run-parallel'): { bin: string; entry: string } {
  const compiled = path.join(import.meta.dirname, '..', 'cli', `${name}.js`);
  // Bản đã biên dịch chạy bằng chính `node` đang chạy tiến trình này — không
  // cần tsx, và không cần đoán xem nó được cài ở đâu.
  if (existsSync(compiled)) return { bin: process.execPath, entry: compiled };

  const source = path.join(import.meta.dirname, '..', 'cli', `${name}.ts`);
  return { bin: path.resolve('node_modules/.bin/tsx'), entry: source };
}

export function track(child: ReturnType<typeof spawn>, signature: string, label: string): void {
  runChildren.add(child);
  if (child.pid !== undefined) orphans.add(child.pid, signature, label);
  const forget = () => {
    runChildren.delete(child);
    if (child.pid !== undefined) orphans.remove(child.pid);
  };
  child.on('close', forget);
  child.on('error', forget);
}

export interface RunSuiteOutcome {
  code: number | null;
  stopped: boolean;
  reportPaths: string[];
  runDirs: string[];
}

export function runSuite(
  platform: string,
  tag: string | undefined,
  headed: boolean,
  includeQuarantined: boolean,
  log: (l: string) => void,
  /** One named device, when the picker chose exactly one. Otherwise the default. */
  device?: string,
  /**
   * SIT / UAT / prod. Local runs only — Device Farm has no route to those
   * servers, so the farm card deliberately offers no such choice.
   */
  env?: string,
  /** Limit a Studio workflow to the feature generated by that workflow. */
  feature?: string,
  /** Extra scenario attempts, used only after a locator-classified failure. */
  locatorRetries?: number,
  /**
   * Lấy app ở đâu cho lượt này: bản đã cài sẵn trên máy, hay bản đã tải lên.
   *
   * Hỏi ở màn chạy chứ không phải ở cấu hình, vì câu trả lời đổi theo từng lượt:
   * sáng chạy trên bản vừa cắm máy cài tay, chiều chạy lại trên bản build mới.
   */
  appSource?: 'device' | 'upload',
  /** Park shared-store changes in each run directory for one coordinator to merge. */
  deferSharedWrites = false,
  /**
   * Config của RIÊNG lượt này — một job mang snapshot chạy trên đúng snapshot
   * ấy, trong thư mục cách ly. Xem [jobWorkspace.ts](./jobWorkspace.ts).
   * Bỏ trống là config thường của máy này.
   */
  configFile?: string,
): Promise<RunSuiteOutcome> {
  return new Promise<RunSuiteOutcome>((resolve, reject) => {
    const { bin, entry } = cliCommand('run');
    const args = [
      entry,
      '--platform',
      platform,
      ...(configFile ? ['--config', configFile] : []),
      ...(device ? ['--device', device] : []),
      ...(env ? ['--env', env] : []),
      ...(feature ? ['--feature', feature] : []),
      ...(locatorRetries !== undefined ? ['--locator-retries', String(locatorRetries)] : []),
      ...(appSource ? ['--app-source', appSource] : []),
      ...(appSource === 'upload' && platform !== 'web' ? ['--reinstall'] : []),
      ...(deferSharedWrites ? ['--defer-shared-writes'] : []),
      ...(tag ? ['--tag', tag] : []),
      ...(headed ? ['--headed'] : []),
      ...(includeQuarantined ? ['--include-quarantined'] : []),
    ];
    log(`$ tsx ${args.join(' ')}`);

    const child = spawn(bin, args, { env: process.env });
    // Tag từ UI đã mang sẵn dấu @; thêm một cái nữa thành "@@feature-dang-nhap"
    // trong danh sách lượt chạy đang sống.
    const label = `${platform}${device ? ` · ${device}` : ''}${tag ? ` · ${tag.startsWith('@') ? tag : `@${tag}`}` : ''}`;
    track(child, 'src/cli/run.ts', `run ${label}`);
    // Mọi dòng đi qua sổ lượt chạy đang sống, không chỉ qua đường dây SSE của
    // tab đã bấm nút. Đó là thứ cho phép một trang khác nối lại sau khi reload.
    const live = beginActiveRun(label, 'run');
    const reportPaths: string[] = [];
    const runDirs: string[] = [];
    const pipe = (chunk: Buffer) => chunk.toString().split('\n').filter(Boolean).map(cleanLog).forEach((line) => {
      const report = /^\[run\] report -> (.+)$/.exec(line)?.[1]?.trim();
      if (report && !reportPaths.includes(report)) reportPaths.push(report);
      // Con báo thư mục của nó ở dòng này; từ đây log ghi được xuống đĩa, và
      // những dòng đã trôi qua được ghi bù.
      const dir = /^\[run:dir\] (.+)$/.exec(line)?.[1]?.trim();
      if (dir) {
        const absoluteDir = path.resolve(dir);
        if (!runDirs.includes(absoluteDir)) runDirs.push(absoluteDir);
        live.attachDir(absoluteDir);
      }
      live.push(line);
      log(line);
    });
    child.stdout.on('data', pipe);
    child.stderr.on('data', pipe);
    child.on('error', (err) => { runChildren.delete(child); endActiveRun(live); reject(err); });
    child.on('close', (code) => {
      runChildren.delete(child);
      const stopped = code === null || code === 130 || code === 143;
      log(
        code === 0
          ? '\n✓ Tất cả test đã pass.'
          // Exit 2 means nothing failed but not everything ran. Saying "tất cả
          // test đã pass" here would be false: the scenarios that were skipped
          // are precisely the ones somebody just edited.
          : code === 2
            ? '\n✎ Test đã chạy không có lỗi, nhưng có kịch bản chưa duyệt nên chưa được chạy — xem danh sách bên trên.'
            : stopped
              ? '\n⊘ Test đã bị dừng.'
              : `\n✗ Test kết thúc với lỗi (mã ${code}) — xem log bên trên để biết chi tiết.`,
      );
      endActiveRun(live);
      resolve({ code, stopped, reportPaths, runDirs });
    });
  });
}

export interface PickedDevice { platform: 'android' | 'ios'; id: string; }

export function parseDeviceToken(token: string): PickedDevice | null {
  const [platform, ...rest] = token.split(':');
  const id = rest.join(':');
  if (!id || (platform !== 'android' && platform !== 'ios')) return null;
  return { platform, id };
}

export async function isNamedDevice(picked: PickedDevice, configFile: string): Promise<boolean> {
  return Boolean(await configIdFor(picked, configFile));
}

/**
 * `id` trong config của chiếc máy mà job nhắm tới — hoặc `undefined`.
 *
 * Job có thể gọi tên máy bằng `id` trong config ("sm-s918b") hoặc bằng udid
 * ("R5CW525G35Y"): màn hình cũ gửi cái thứ nhất, sổ thiết bị thì khoá theo
 * cái thứ hai. Cả hai đều phải dẫn về `--device <id>`, vì đó là thứ duy nhất
 * `run.ts` nhận.
 *
 * Vì sao quan trọng: thiếu phép quy đổi này, một job nhắm udid sẽ chạy KHÔNG
 * ghim máy — Appium tự chọn lấy một chiếc trong số đang cắm. Người dùng chọn
 * emulator, lượt chạy diễn ra trên chiếc điện thoại thật bên cạnh, và report
 * trả về trông hoàn toàn bình thường.
 */
export async function configIdFor(
  picked: PickedDevice,
  configFile: string,
): Promise<string | undefined> {
  try {
    const cfg = await loadConfig(configFile);
    const listed = picked.platform === 'android' ? cfg.android.devices : cfg.ios.devices;
    if (!listed?.length) return undefined;
    const found = listed.find((device) =>
      device.id === picked.id || device.udid === picked.id || device.deviceName === picked.id);
    return found?.id;
  } catch {
    return undefined;
  }
}

/**
 * Runs the suite on several devices, by handing the job to the parallel CLI.
 *
 * Deliberately not reimplemented here. Port validation, per-device log
 * prefixes, and the single sequential merge that keeps three devices from
 * erasing each other's learnings all live in run-parallel.ts; a second copy
 * inside the server is a second copy to get wrong.
 */
export function runSuiteParallel(
  platform: string,
  devices: string[],
  tag: string | undefined,
  includeQuarantined: boolean,
  log: (l: string) => void,
  env?: string,
  appSource?: 'device' | 'upload',
) {
  return new Promise<void>((resolve, reject) => {
    const { bin, entry } = cliCommand('run-parallel');
    const args = [
      entry,
      '--platform', platform,
      '--devices', devices.join(','),
      ...(env ? ['--env', env] : []),
      ...(appSource ? ['--app-source', appSource] : []),
      ...(appSource === 'upload' ? ['--reinstall'] : []),
      ...(tag ? ['--tag', tag] : []),
      ...(includeQuarantined ? ['--include-quarantined'] : []),
    ];
    log(`$ tsx ${args.join(' ')}`);

    const child = spawn(bin, args, { env: process.env });
    track(child, 'src/cli/run-parallel.ts', `run song song ${platform}`);
    const pipe = (chunk: Buffer) =>
      chunk.toString().split('\n').filter(Boolean).map(cleanLog).forEach(log);
    child.stdout.on('data', pipe);
    child.stderr.on('data', pipe);
    child.on('error', (err) => { runChildren.delete(child); reject(err); });
    child.on('close', (code) => {
      runChildren.delete(child);
      const stopped = code === null || code === 130 || code === 143;
      log(
        code === 0
          ? `\n✓ Tất cả ${devices.length} thiết bị đã pass.`
          : stopped
            ? '\n⊘ Test đã bị dừng.'
            : `\n✗ Có thiết bị fail (mã ${code}) — xem log theo tiền tố [tên máy] ở trên.`,
      );
      resolve();
    });
  });
}

/**
 * Kills every test suite this server started, and the WebDriverAgent runner
 * with it.
 *
 * Killing only the suite leaves the `xcodebuild` running WDA orphaned to init,
 * which keeps the XCUITest alive on the phone: iOS goes on showing its
 * "Automation running — hold both volume buttons to stop" banner, and the next
 * iOS session inherits a runner nobody is talking to. Stopping the run has to
 * mean stopping what the run left on the device.
 */
export async function stopSuite(): Promise<{ stopped: boolean; wda: boolean }> {
  let stopped = 0;
  for (const child of runChildren) {
    if (child.exitCode !== null) continue;
    // SIGTERM first; the tsx/node process should clean up and exit. A parallel
    // run passes it on to its own per-device children before merging what they
    // managed to learn, so stopping is not the same as discarding.
    child.kill('SIGTERM');
    stopped += 1;
  }
  const wda = await stopWebDriverAgent();
  return { stopped: stopped > 0, wda };
}
